### ISSUE TITLE
Add animation: when starting a game

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/LightsOff#55]
When you start/restart a game, there could be a quick animation.

When starting a specific level:
* turn off all tiles one-by-one from left-to-right, row-by-row top down. (in a 1/4 second?)
* turn on tiles of the level one-by-one from right-to-left, ror-by-row buttom up. (in a 1/4 second?)

When starting a random level:
* turn off all tiles one-by-one from left-to-right, row-by-row top down. (in a 1/4 second?)
* show 4 or 8 random patterns in quick succession (should take no more than 1 second), before displaying the final random puzzle.

There could be different patterns how the board is cleared or set up, that could be used randomly, if anyone enjoys playing around with that sort of thing.

**Comment by owenca** [comment]
Turning on buttons one by one (when starting a non-random puzzle) and turning them off one by one can present a problem when there are many buttons to flip. For example, a Level 63 8x8 puzzle can have 40+ buttons to be turned on/off. Perhaps one row/column/diagonal at a time would work.

**Comment by humdingerb** [comment]
The turning on/off could speed up with the board size, so the whole animation is always 1/2 s long. Whatever works best for you. :)

**Comment by owenca** [comment]
Turning on the buttons one by one is not too bad after all because we only have to deal with the 5x5 grid, which has at most 25 buttons to flip on. :)

However, clearing the board one button at a time in addition to the animation before displaying a puzzle would take too long, IMO. It would be perfectly ok to clear the board all at once, sort of like pulling the plug. It's like playing chess: wipe all the pieces off the board and then set them one by one to start a new game.

**Comment by humdingerb** [comment]
Sure. Or turn all on at once, then quickly turn all off. Wait 1/4s, then begin lighting the new pattern. Whatever you decide to do is fine. I'm very happy with these little animations. They make the game less static, even though they are really only small details few people will 'consciously' see.

**Comment by owenca** [comment]
I like your ideas. The animations are cool!
